# Generated by Django 4.2.7 on 2023-11-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_management.topic'),
        ),
    ]
