# Generated by Django 4.2.7 on 2023-11-23 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import item_management.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_management', '0006_remove_comment_created_at_remove_like_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='optional_fields',
            field=models.JSONField(null=True, validators=[item_management.validators.validate_optional_fields]),
        ),
    ]
