# Generated by Django 4.2.7 on 2023-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0007_item_creator_alter_item_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='optional_fields',
        ),
        migrations.AddField(
            model_name='item',
            name='optional_fields',
            field=models.ManyToManyField(to='item_management.optionalfield'),
        ),
    ]
