# Generated by Django 4.2.7 on 2023-11-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0009_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='like',
            name='item',
        ),
    ]
